
services:
  backend:
    build: ./backend
    container_name: utopiahire-backend
    cap_add:
      - NET_ADMIN    # allows network administration (needed for iptables)
      - NET_RAW      # allows raw packet access
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - utopia_net

  frontend:
    build: ./frontend
    container_name: utopiahire-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    healthcheck:
      disable: true
    networks:
      - utopia_net

networks:
  utopia_net:
    external: true
    name: utopiahire-main_default
