version: '3.8'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # ADD THIS
      - /usr/bin/docker:/usr/bin/docker             # ADD THIS
    group_add:
      - "999"   # docker group — allows jenkins user to use the socket
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: utopiahire-sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: utopiahire-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: utopiahire-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:latest
    container_name: utopiahire-suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/rules:/etc/suricata/rules
      - ./suricata/logs:/var/log/suricata
    command: -i lo --set af-packet.0.interface=lo --set default-rule-path=/etc/suricata/rules -S /etc/suricata/rules/utopiahire.rules
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: utopiahire-dashboard
    ports:
      - "8501:8501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./security-reports:/app/security-reports
      - ./suricata/logs:/app/suricata/logs
    environment:
      - OPENAI_API_KEY=${AI_API_KEY}
    restart: unless-stopped

volumes:
  jenkins_data:
  sonar_data:
  sonar_logs:
  grafana_data: