sonar.projectKey=utopiahire
sonar.projectName=UtopiaHire
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/.git/**,**/security-reports/**,**/tests/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/__init__.py
sonar.scm.provider=git
